services:
  - type: web
    name: speedleads-server
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: FRONTEND_URL
        value: https://app.uniclick.io
      - key: BACKEND_URL
        value: https://speedleads-server.onrender.com
      # Supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      # Auth0
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://app.uniclick.io/login/callback
      # Google APIs
      - key: GOOGLE_VISION_API_KEY
        sync: false
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
      # SendGrid
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        value: affiliates@uniclick.io
      - key: SENDGRID_INVITE_TEMPLATE_ID
        sync: false
      # Stripe
      - key: STRIPE_SECRET_KEY
        sync: false
      # JWT
      - key: JWT_SECRET
        sync: false
      # OpenAI
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
